name: Weekly refresh of recent contract data

on:
  # Run every Sunday at midnight UTC
  schedule:
    - cron: "0 0 * * 0"
  # Also allow manual triggering
  workflow_dispatch:

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Compute fiscal years and fetch contract data
        run: |
          # Determine current calendar year and month
          CURRENT_YEAR=$(date +%Y)
          MONTH=$(date +%m)

          # Fiscal year logic:
          # If the month is October (10) or later, the fiscal year is next calendar year.
          if [ "$MONTH" -ge 10 ]; then
            FISCAL_YEAR=$((CURRENT_YEAR + 1))
          else
            FISCAL_YEAR=$CURRENT_YEAR
          fi

          echo "Current Fiscal Year: $FISCAL_YEAR"

          # Calculate current and past two fiscal years
          FY1=$FISCAL_YEAR
          FY2=$((FISCAL_YEAR - 1))
          FY3=$((FISCAL_YEAR - 2))
          echo "Fetching data for fiscal years: $FY1, $FY2, $FY3"

          # Run the Python script with the fiscal years and default output directory
          python fetch-contracts.py -fy $FY1 $FY2 $FY3

      - name: Commit updated CSV files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          message: 'Update NASA contract CSV files'
          add: 'data/*.csv'